### ISSUE TITLE
Error using bodyFilter with jsonPath 

### ISSUE THREAD

**Issue by tfpolachini** [zalando/logbook#1049]
I'm using logbook version 2.9.0 and I'd like to mask a specific attribute (cpf) in the request and response body. The bean that I created is below:

```
@Bean 
public Logbook logbook() {
   return Logbook.builder()
        .bodyFilter(jsonPath("$.cpf").replace(compile("(\\d{3})(\\d{3})(\\d{3})-?(\\d{2})"), "$1.XXX.$3-XX"))
        .bodyFilter(jsonPath("$.results.client.cpf").replace(compile("(\\d{3})(\\d{3})(\\d{3})-?(\\d{2})"), "$1.XXX.$3-XX"))
        .build();
}
```
When I make an request with body {"cpf": "21343575698"}, an error occur: "Missing property in path $['results']","trace":"com.jayway.jsonpath.PathNotFoundException: Missing property in path $['results']"

is there something wrong with my configuration?

Thanks a lot.

**Comment by whiskeysierra** [comment]
Are you configuring JsonPath anywhere, outside of the code snippet that you shared?
Can you provide a failing test case, to reproduce this?

**Comment by GurevichAleksey** [comment]
For example, you can get error when you us logbook, jsonpathbody filters and spring security
![image](https://user-images.githubusercontent.com/3891762/119867679-d2216b00-bf26-11eb-96ba-b13edf2ccd2b.png)

The problem is that Logbook filter after spring security chain try to log request body (but for GET request body is null or empty), so i get exception in jsonpath

**Comment by PascalSchumacher** [comment]
As far as I know the JsonPath implementation used by logbook can throw exceptions (unless configured otherwise (I do not see this configuration in the logbook source code)) when part of the path are not present in the Json.

This could be the cause of the problem, but without a example to replicated it is hard to tell.

**Comment by whiskeysierra** [comment]
This seems to be a bug in the JsonPath-based body filter. Anyone care to create a test to reproduce it?

**Comment by SpiReCZ** [comment]
@tfpolachini As far as my own experience goes with new jsonPath filters i can tell that it still needs some work before it can become usable in real world applications.

Problems:
- if parent object (jsonPath("$.a.b")) of filtered path (jsonPath("$.a.b.c")) is null, then com.jayway.jsonpath.PathNotFoundException is thrown
- jsonPath filters every Request and Response (with different json bodies), throwing com.jayway.jsonpath.PathNotFoundException (because of previous point)
- jsonPath filters every Request and Response, creating potentional performance issues if more filters are applied -> this is due to filters being applied to another http bodies it doesn't belong to, and the filters do empty work most of the time basically

Our use case scenarios:
- Filter Requests and Responses based on their Request path, so jsonPath filters are applied only to specific Request path
- Filter won't ever fail on com.jayway.jsonpath.PathNotFoundException when filtering json body

I have created implementation tailored to our use case scenarios which also eliminates or mitigates mentioned issues.
@whiskeysierra Maybe i can provide our JsonPathBodyFilters edit as an example, or even some more code.

**Comment by SpiReCZ** [comment]
> For example, you can get error when you use logbook, jsonpathbody filters and spring security
> 
> Here logbook try to log GET authenticated request
> ![image](https://user-images.githubusercontent.com/3891762/119867679-d2216b00-bf26-11eb-96ba-b13edf2ccd2b.png)
> 
> The problem is that Logbook filter after spring security chain try to log request body (but for GET request body is null or empty), so i get exception in jsonpath

This seems at first like a possible nullability issue in JsonPathBodyFilters. But the implementation from what i remember contains a check for json contentType which should result to the filter not being applied when GET request does not have a body. I might check it tomorrow..

**Comment by swanandi25** [comment]
@whiskeysierra are jsonpath body filters are still experimental feature or can be used in real time projects?

**Comment by StephenOkeleke97** [comment]
It looks like the problem of throwing an exception if a path is missing still exists. This prevents valid paths from being parsed and filtered
