### ISSUE TITLE
Logging both request and response in a single line

### ISSUE THREAD

**Issue by chaninja** [zalando/logbook#1170]
Hi, 
I tried a custom solution to log both request and response in the same log statement. Not sure if this is the right way to go about it. See attached code and please advise. I am using Spring-Boot with maven.
Thanks
Chandra

//Implementation of custom Sink class
import java.io.IOException;

import org.json.JSONObject;
import org.zalando.logbook.Correlation;
import org.zalando.logbook.HttpLogFormatter;
import org.zalando.logbook.HttpLogWriter;
import org.zalando.logbook.HttpRequest;
import org.zalando.logbook.HttpResponse;
import org.zalando.logbook.Precorrelation;
import org.zalando.logbook.Sink;
import lombok.AllArgsConstructor;

@AllArgsConstructor
public class LogRequestAndResponseTogetherSink implements Sink {
	private final HttpLogFormatter formatter;
    private final HttpLogWriter writer;

    @Override
    public boolean isActive() {
        return writer.isActive();
    }

    @Override
    public void write(final Precorrelation precorrelation, final HttpRequest request) throws IOException {
        //writer.write(precorrelation, formatter.format(precorrelation, request));
    }

    @Override
    public void write(final Correlation correlation, final HttpRequest request, final HttpResponse response)
            throws IOException {
        //writer.write(correlation, formatter.format(correlation, response));
    	String requestMessage = formatter.format(correlation, request);
    	JSONObject reqJson = new JSONObject(requestMessage);
    	String responseMessage = formatter.format(correlation, response);
    	JSONObject respJson = new JSONObject(responseMessage);

    	JSONObject combinedReqResp = new JSONObject();
    	combinedReqResp.put("requestMessage", reqJson);
    	combinedReqResp.put("responseMessage", respJson);
    	writer.write(correlation,  combinedReqResp.toString());
    }	
}

//bean configuration
@Bean
  public Sink logRequestResponse() {
	  return new LogRequestAndResponseTogetherSink(
	            new JsonHttpLogFormatter(),
	            new DefaultHttpLogWriter());
  }

**Comment by skjolber** [comment]
@chaninja what is your motivation for doing that?

**Comment by chaninja** [comment]
I want to have both request and response captured in a single log. So we can monitor/search and analyze api endpoints for various parameters like duration, failure rate, etc,

Chandra

________________________________

**Comment by skjolber** [comment]
Ok, that is normally done by adding ids to the request/response statements, not by outputting them together on a single line, you'll not be happy with the results of that because you normally want some log statements inbetween request and response. 

Did you see the [correlation](https://github.com/zalando/logbook#correlation)?

**Comment by whiskeysierra** [comment]
@chaninja The answer that @skjolber gave is what I'd suggest as well. Correlation IDs within both the request and the response log lines is the way that should work for most users and give you the best of everything:

1. Requests are logged as soon as they arrive
2. Requests and responses can be correlated

If you're willing to accept the following consequences, there is a way to do it cleanly:

1. Requests are logged only when a response is logged (might be out of order with your normal application logging)
2. Requires more manual coding (see below) 
3. Correlation is easier to do

Steps you should be looking into to log both requests and responses on the same line:

1. Custom strategy  
   Implement a custom `Strategy` that calls `Sink#writeBoth` instead of `Sink#write`.  
   You might get away with using one of the existing `Strategy` implementations and configure them in a way that makes them behave like that (e.g. `StatusAtLeastStrategy` with a minimum status of `0`).
2. Custom Sink  
   Implement a custom `Sink` that formats both the request and response in whatever format you want to combine them before handing them over to the Logger or `HttpLogWriter`.
   You might be able to re-use the existing formatters and writers and use them a bit differently, like produce two JSON bodies and hand-craft the enclosing document by hand. Or you use full custom formatters that produce data structures (maps).
