### ISSUE TITLE
Log4J Vulnerability

### ISSUE THREAD

**Issue by sdiemert** [zalando/logbook#1238]
Given the dramatic Log4J vulnerability over the last few days, I had two questions:

1) Does Logbook depend on Log4J in anyway? (I think not, but always worth asking...)

2) Does the same vulnerability exist in Logbook? 

Sorry if this is a silly issue. Feel free to close promptly if this isn't a concern.

**Comment by whiskeysierra** [comment]
Logbook relies on slf4j as its logging abstraction.
We may use log4j for some tests, but then the dependencies are scoped to test.

Having said that, users of Logbook that happen to use log4j as their logging facility of choice should be very diligent.
The very nature of logbook makes users rather susceptible to the vulnerability, since most if not all user supplied inputs are being logged.
