### ISSUE TITLE
JsonHttpLogFormatter failed to render JSON log when request / response body is not met JSON spec

### ISSUE THREAD

**Issue by dai0304** [zalando/logbook#139]
For example

```
$ curl http://example.com -XPUT --data 'this is not json' -H 'Content-Type: application/json'
```

generates following log.

```
{"origin":"remote","type":"request", ...snip... ,"body":this is not json}
```

**Comment by whiskeysierra** [comment]
I'd consider this to be in violation of [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.5), since the declared content type does in fact not match with the actual content:

> 3.1.1.5.  Content-Type
>
>   The "Content-Type" header field indicates the media type of the
   associated representation: either the representation enclosed in the
   message payload or the selected representation, as determined by the
   message semantics.  The indicated media type defines both the data
   format and how that data is intended to be processed by a recipient,
   within the scope of the received message semantics, after any content
   codings indicated by Content-Encoding are decoded.

We reasonably rely on a correct content type to detect JSON in order to avoid *content sniffing*:

>  In practice, resource owners do not always properly configure their
   origin server to provide the correct Content-Type for a given
   representation, with the result that some clients will examine a
   payload's content and override the specified type.  Clients that do
   so risk drawing incorrect conclusions, which might expose additional
   security risks (e.g., "privilege escalation").  Furthermore, it is
   impossible to determine the sender's intent by examining the data
   format: many data formats match multiple media types that differ only
   in processing semantics.  Implementers are encouraged to provide a
   means of disabling such "content sniffing" when it is used.

**Comment by dai0304** [comment]
We implement the Web API to input and output JSON, and it can not control what kind of request the client sends.
I think that if the Content-Type and actual body format do not match, logs should output correct JSON (even if body is ommited).

**Comment by whiskeysierra** [comment]
> if the Content-Type and actual body format do not match

I don't see a way to make this work other than actually trying to parse JSON which is a quite heavy and expensive operation to cover this corner case. What I could imagine as a feature request would be to disable the JSON-inlining that we have right now and make it configurable, e.g. 

```yaml
logbook.format.json.inline-body: false
```

**Comment by dai0304** [comment]
OK, I'll implement custom `HttpLogFormatter`.
Thanks a lot!!
