### ISSUE TITLE
Logbook doesn't work with spring boot 3

### ISSUE THREAD

**Issue by evkaky** [zalando/logbook#1485]
I'm following the documentation https://github.com/zalando/logbook#spring-boot-starter trying to make `WebClient` logging all exchanges, but here is a minimal code sample to make sure logbook + spring boot web client = nothing get logged
`build.gradle.kts`:
```kotlin
plugins {
    java
    id("org.springframework.boot") version "3.0.5"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:3.0.5"))
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.zalando:logbook-spring-boot-starter:2.16.0")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}
```

`src/main/resources/application.yml`:
```yaml
spring:
  main.web-application-type: none

logging.level:
  org.zalando.logbook: trace

logbook:
  format.style: http
  filter.enabled: false
```

`SpringApplication.java`:
```java
@SpringBootApplication
public class MyApp {
    public static void main(String[] args) {
        SpringApplication.run(MyApp.class);
    }

    @Bean
    public ApplicationRunner onStart(WebClient.Builder webClientBuilder) {
        return args -> {
            var webClient = webClientBuilder
                .baseUrl("https://jsonplaceholder.typicode.com")
                .build();

            Todo resp = webClient
                .get()
                .uri("todos/{id}", 1)
                .retrieve()
                .bodyToMono(Todo.class)
                .block();

            System.out.println(resp.title);
        };
    }
}

class Todo {
    public int id;
    public int userId;
    public String title;
    public boolean completed;
}
```
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/4532181/232755065-b005dbb3-4103-4834-955e-c642b2bc7b0a.png">
As you can see, nothing got logged

**Comment by Larkhis** [comment]
Hello @evkaky 
In order to make logbook work with webflux, you have just to include this dependency logbook-spring-webflux.
And inject LogbookExchangeFilterFunction to your client.
Here is the snippet of SpringApplication.java :
`@SpringBootApplication
public class LogbookWebClientApplication {

	public static void main(String[] args) {
		SpringApplication.run(LogbookWebClientApplication.class, args);
	}

	@Bean
	Logbook logbook() {
		return Logbook.create();
	}

	@Bean
	public ApplicationRunner onStart(WebClient.Builder webClientBuilder, Logbook logbook) {
		return args -> {
			var webClient = webClientBuilder
					.baseUrl("https://jsonplaceholder.typicode.com")
					.filter(new LogbookExchangeFilterFunction(logbook))
					.build();

			Todo resp = webClient
					.get()
					.uri("todos/{id}", 1)
					.retrieve()
					.bodyToMono(Todo.class)
					.block();
		};
	}

}`
At startup you should have logs as follow 
`2023-04-20T09:33:56.322+02:00 TRACE 5385 --- [ctor-http-nio-3] org.zalando.logbook.Logbook              : Outgoing Request: b38c306d3a9321da
Remote: localhost
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
2023-04-20T09:33:56.346+02:00 TRACE 5385 --- [ctor-http-nio-3] org.zalando.logbook.Logbook              : Incoming Response: b38c306d3a9321da
Duration: 535 ms
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Age: 24475
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
Cache-Control: max-age=43200
CF-Cache-Status: HIT
CF-RAY: 7babb3af8852016f-CDG
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 20 Apr 2023 07:33:55 GMT
Etag: W/"53-hfEnumeNh6YirfjyjaujcOPPT+s"
Expires: -1
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Pragma: no-cache
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=QlbxHWPNBszzAYaDHr2%2BsOajOdU3NLHnQJHEfJtnJGV0rVPBS7OCXv2r%2Fw2f26QR5XrM67Etn18%2BKNkbi%2FVLpbWhVrm7UCMb%2FehyhxPkK4lOJsR%2B8W4zNgxh%2FQN0EV8C49g1aXCDQwmZAPoGpN5v"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Transfer-Encoding: chunked
Vary: Origin, Accept-Encoding
Via: 1.1 vegur
X-Content-Type-Options: nosniff
X-Powered-By: Express
X-Ratelimit-Limit: 1000
X-Ratelimit-Remaining: 999
X-Ratelimit-Reset: 1678148633

{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
`
Hope that help you.

**Comment by kasmarian** [comment]
The autoconfiguration part should be fixed in the next release. I'll resolve the issue. Feel free to reopen if you still need support here.

**Comment by as87321234** [comment]
Springboot 3.3.1  with logbook-spring-boot-start version 3.9.0

Thx

**Comment by thestroke82** [comment]
> For spring-webflux application you'd need to use `logbook-spring-boot-webflux-autoconfigure` as a dependency.
> 
> But it looks like the [org.springframework.boot.autoconfigure.AutoConfiguration.imports](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration) file is missing in `logbook-spring-boot-webflux-autoconfigure` module. Without it, the `LogbookWebFluxAutoConfiguration` class is not loaded by default. Until it's added, you'd need to add the filter directly as @Larkhis suggested or Import `LogbookWebFluxAutoConfiguration` to your spring boot app. I'll open a PR for it.

In my Spring Boot WebFlux project, I am unable to generate any logs using Logbook.

Here is the relevant section from my pom.xml:
```
<dependency>
      <groupId>org.zalando</groupId>
      <artifactId>logbook-spring-boot-autoconfigure</artifactId>
      <version>3.9.0</version>
    </dependency>
    <dependency>
      <groupId>org.zalando</groupId>
      <artifactId>logbook-spring-boot-webflux-autoconfigure</artifactId>
      <version>3.9.0</version>
    </dependency>
    <dependency>
      <groupId>org.zalando</groupId>
      <artifactId>logbook-netty</artifactId>
      <version>3.9.0</version>
    </dependency>
```
    
The configuration in application.yml is as follows:
 
 ```
logbook:
  format: json
  strategy: default
  filter:
    enabled: true
    exclude:
      - /swagger
      - /api-docs
      - /actuator
  obfuscate:
    headers:
      - Authorization
      - Cookie
    parameters:
      - password
    body:
      patterns:
        - '"password": ".*"'
  write:
    level: DEBUG
    category: logbook.log
  max-body-size: 1000
  exclude:
    content-types:
      - application/octet-stream   

```

**Comment by whiskeysierra** [comment]
You've missed to post your logging (framework) configuration.

**Comment by thestroke82** [comment]
> You've missed to post your logging (framework) configuration.

Updated

**Comment by whiskeysierra** [comment]
You configure Logbook to use the category (aka logger name) "category: logbook.log" but then you configure your logging framework to change the log level of "org.zalando". Those need to be aligned. You can just delete the line with "category" and then it should already work.

(This has nothing to do with Logbook, technically. Just logging framework configuration.)

**Comment by thestroke82** [comment]
I removed the category entirely, but I'm still not seeing any output. I also set write.level = INFO for both Logbook and the root logger, but still I see no result.

**Comment by whiskeysierra** [comment]
The full category name is `org.zalando.logbook.Logbook` (see https://github.com/zalando/logbook?tab=readme-ov-file#writing). Maybe your logging framework needs to configure the full name and not just the prefix. No idea.

**Comment by thestroke82** [comment]
> DefaultHttpLogWriter

Turns out it works when trace is enabled. It is not picking up this setting:

```
  write:
    level: DEBUG
```

**Comment by whiskeysierra** [comment]
Could it be that this feature was removed at some point?

**Comment by thestroke82** [comment]
I am sure it was. I mean, I hope it was just moved somewhere else.
