### ISSUE TITLE
Logbook not read logback configuration from logback-spring.xml

### ISSUE THREAD

**Issue by caoy4** [zalando/logbook#1648]
## Description
When I debug the issue, I found org.zalando.logbook.core.DefaultHttpLogWriter#isActive() is false, but I have already configured <logger name="org.zalando.logbook" level="TRACE" /> in the logback-spring.xml (this is also a SpringBoot auto-box default file location), the logbook does not print the log.

When I change the file name to logbak.xml, it works.

## Context
Spring Boot 3.1.3
org.zalando:logbook-spring-boot-starter:3.5.0

## Your Environment
Java 17

**Comment by ChristianLohmann** [comment]
Hi, Logbook does not read logback's configuration and it is not intended to do so. In order to make Logbook logging requests, set the log level of `org.zalando.logbook` to `TRACE`. In case using the XML variant of Logbacks configuration add `<logger name="org.zalando.logbook" level="TRACE"/>` to `logback-spring.xml`.
Is that what you were trying to accomplish?
