### ISSUE TITLE
How to log request/response based on response status

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/logbook#165]
With a high load it could be wasteful to log all request/responses.
It should be possible to log only failed request responses, e.g. where response status is not 20x.

**Comment by whiskeysierra** [comment]
With the current tools this could be achieved with some rather hacky formatter + logger implementations. From the top of my head I'd say a cleaner way would be to introduce markers for log messages generated by logbook: https://logging.apache.org/log4j/2.0/manual/filters.html.

I could imagine to expose some properties of the captured messages.

(Not 100% sure if this would work out of the box with the current design since we may not have those infos anymore when logging.)

**Comment by AlexanderYastrebov** [comment]
Maybe in such a case we may change the way we log: log request and response together later if logging is conditional on response properties.

**Comment by whiskeysierra** [comment]
The problem is that the writer does not have enough information at hand at that point. When the response is to be logged it only receives a string, i.e. the formatted response.

**Comment by AlexanderYastrebov** [comment]
But at least status and headers are there. Maybe JSON response could be accessible as well

**Comment by whiskeysierra** [comment]
See https://github.com/zalando/logbook/blob/master/logbook-api/src/main/java/org/zalando/logbook/HttpLogWriter.java#L13. We only have the raw strings at that point.

**Comment by bobross-pg** [comment]
Hello @whiskeysierra , it looks like the fix you added here
- https://github.com/zalando/logbook/commit/254ea4e6c583748f6e77373f08bf22a54f3801cf  (Jul 4, 2017)
was then deleted by you on this commit 52fdcf6f188000b7e6b2d30b1bf04311eb75d7db (2018-10-31)

Is there a new way to be able to log request only for certain response status ?

Thank you,
