### ISSUE TITLE
Logbook 3.7.0 pulls in Lombok as transitive dependency

### ISSUE THREAD

**Issue by bwaldvogel** [zalando/logbook#1705]
When upgrading Logbook from `3.6.0` to `3.7.0` we get a new transitive dependency pulled in: `org.projectlombok:lombok:1.18.30`.
For projects that are not using Lombok, that causes undesired effects. For example, IntelliJ IDEA auto-discovers that Lombok is used in the project and starts suggesting the use of Lombok annotations.

## Steps to reproduce

1. Create a new Gradle / Spring Boot project (use [start.spring.io](https://start.spring.io) or IntelliJ’s native integration)
2. Add the following dependency: `org.zalando:logbook-spring-boot-starter:3.7.0`

## Actual behavior
`./gradlew -q dependencyInsight --dependency lombok` shows that Lombok is pulled in:
```
org.projectlombok:lombok:1.18.30
\--- org.zalando:logbook-spring-boot-autoconfigure:3.7.0
     \--- org.zalando:logbook-spring-boot-starter:3.7.0
```

When downgrading from `3.7.0` to `3.6.0`, the Lombok dependency disappears.

## Expected behavior

The Lombok is not pulled in as it was in version `3.6.0`.

**Comment by kasmarian** [comment]
@msdousti it looks like [this change](https://github.com/zalando/logbook/commit/3004477032652125ee4b302c1d5b4e69ec4ac198#diff-97593056ecbf49ece87cde9da9d7bf29153431ca92e89a86e7f190edd7e5c621R21) started pulling lombok as a compile dependency, because it's declared as such in [spring-boot-dependencies](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-dependencies/build.gradle#L858-L864). Do you think we can revert to using `spring-framework-bom`? Alternatively, we'd need to override the scope for lombok (potentially other dependencies?) in `logbook-spring-boot-autoconfigure` module directly.

**Comment by msdousti** [comment]
@kasmarian
There are several things going on that need a deeper look.

1. The [change you mentioned](https://github.com/zalando/logbook/commit/3004477032652125ee4b302c1d5b4e69ec4ac198#diff-97593056ecbf49ece87cde9da9d7bf29153431ca92e89a86e7f190edd7e5c621R21) only touches the `dependencyManagement` section. By itself, `dependencyManagement` will not include dependencies in a project; it just says that if a dependency is ever requested, this specific version must be used.

2. I tried creating a Gradle and a Maven project including the `Steps to reproduce`. The Gradle project is as mentioned in the ticket, but the Maven project behaves as expected: It does not include Lombok - `mvn dependency:tree -Dincludes=org.projectlombok` returns nothing. See for yourself [here](https://github.com/msdousti/lombok-and-logbook).

As a side note, depending on `spring-framework-bom` in a Spring Boot project is not right, since the BOM file for Spring Framework often includes newer material that might not be compatible with the current version of Spring Boot. When the project does not have Spring Boot as its parent (like here), [it's customary to include spring-boot-dependencies in the dependencyManagement section](https://www.baeldung.com/spring-boot-dependency-management-custom-parent#spring-boot-without-parent-pom).

I'll try to dig deeper why Gradle is not behaving as expected.

**Comment by msdousti** [comment]
@kasmarian I believe the the above PR (#1706) fixes this.

**Comment by msdousti** [comment]
@bwaldvogel Thanks a lot for your report!

It will be great if you create a new ticket mentioning all those "badly scoped" dependencies; I'll then fix them in one PR.

**Comment by bwaldvogel** [comment]
Please see https://github.com/zalando/logbook/issues/1711
