### ISSUE TITLE
QueryParameters#splitEntries fails with java.util.NoSuchElementException

### ISSUE THREAD

**Issue by criedel** [zalando/logbook#20]
Given a URL with an undefined query parameter value ``` http://example.com/?param ``` the ``` QueryParameters#splitEntries ``` will throw a java.util.NoSuchElementException.
The library should either ignore those parameters or support them. IMHO actual error handling should occur in the application code.

**Comment by whiskeysierra** [comment]
It's definitely a bug. We should support *any* format of the query string since according to the official URI specification [RFC3986](http://tools.ietf.org/html/rfc3986#section-3.4) does **not** have a defined format. It's just that most implementations support key value pairs.

> The query component contains non-hierarchical data that, along with
   data in the path component (Section 3.3), serves to identify a
   resource within the scope of the URI's scheme and naming authority
   (if any).  [...]  However, as query components
   are often used to carry identifying information in the form of
   "key=value" pairs and one frequently used value is a reference to
   another URI, [...].

**Comment by whiskeysierra** [comment]
@criedel I created a bugfix including some unit tests. Would this fix your problem?
