### ISSUE TITLE
Logbook resolves localhost address via InetAddress.getLocalHost()

### ISSUE THREAD

**Issue by jmatusewicz-bringmeister** [zalando/logbook#200]
Due to the fact that logbook tries to resolve the localhost address via the java api (https://github.com/zalando/logbook/blob/master/logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/Localhost.java#L9), all requests processed by logbook got slowdown by 5 seconds in my application (https://thoeni.io/post/macos-sierra-java/). I know this not a fail of logbook but maybe it's enough to just use static value to distinguish between local and remote requests.

**Comment by whiskeysierra** [comment]
> to distinguish between local and remote requests

We actually don't use this value to distinguish between local and remote. That's what `origin` is for (either `LOCAL` or `REMOTE`) which is statically set in stone by the corresponding implementations, see:
- https://github.com/zalando/logbook/blob/b2eecfbbb84b031c1980e549e498eca86c62f405/logbook-servlet/src/main/java/org/zalando/logbook/servlet/RemoteRequest.java#L53
- https://github.com/zalando/logbook/blob/2497ce32c249190dfef303cbf95b72e28989061d/logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java#L38

I see several options now:
1. We make the `Localhost` interface as well as the `LogbookHttpRequestInterceptor` constructor that uses it public. Users are then free to supply their own implementation which should be as simple as it gets, since it's a single-method interface:
```java
return () -> "127.0.0.1";
```
2. We add support for a system property that allows to statically define the local address, e.g. `localbook.localhost-address`. If set the current implementation could step back and just use the supplied value directly without any overhead.
3. Instead of calling `InetAddress.getLocalHost().getHostAddress()` on every outgoing request, we actually only call it once on startup and cache it for the remaining lifetime of the application. I'm not familiar with this, but I'd assume that the underlying address could change (?) at runtime. This would obviously no longer work then.

@jmatusewicz-bringmeister @lukasniemeier-zalando Any preferences?

**Comment by whiskeysierra** [comment]
4. Get rid of localhost address for outgoing requests completely since it in the best case unreliable and in the worst case harmful (case and point: this very issue).

**Comment by whiskeysierra** [comment]
@jmatusewicz-bringmeister See #201

**Comment by lukasniemeier-zalando** [comment]
My votes goes to (4) - just hardcode "localhost" there.

**Comment by jmatusewicz-bringmeister** [comment]
I'm fine to hardcode "localhost" as proposed by @lukasniemeier-zalando as I do not see any real world scenario where its important to know what exactly local ip address the machine has configured nor any scenario where the localhost ip address would change at runtime of the application.

**Comment by whiskeysierra** [comment]
@jmatusewicz-bringmeister I released 1.5.4 to central. Thanks for bringing this up

**Comment by jmatusewicz-bringmeister** [comment]
Thank you @whiskeysierra & @lukasniemeier-zalando for your lightning fast support.
