### ISSUE TITLE
Add logbook.write.body_max_size as configuration parameters

### ISSUE THREAD

**Issue by boure** [zalando/logbook#267]
Add `logbook.write.body_max_size` as a configuration so that the size of the logged body can be limited to a given number of characters.

## Context
Some of our services return response with body in the order of 10MBs, which can be a load on logging. While we are still interested in reading some of the body content, having this configuration would allow us to use logbook from the configuration only while avoiding over-large bodies (which can break the service).

**Comment by whiskeysierra** [comment]
To clarify: Compared to chunking (what we already support), you're rather looking for truncating, right?

**Comment by boure** [comment]
yes. Chunking is fine but it doesn't prevent display very large bodies in itself.

I hadn't considered that the whole log entry could be truncated - just the body part.
I guess truncating the entry would be more difficult and less desirable.

**Comment by whiskeysierra** [comment]
Truncating the whole log message is actually easy. I believe both logback and log4j2 support it out of the box. But you're right, it's not desirable, since it breaks our format, eg JSON. Truncating just the body makes way more sense.

Would you be willing to propose a pull request? You can take the chunking feature as a blueprint on how to implement it.

**Comment by boure** [comment]
:+1: will do.
