### ISSUE TITLE
Annotation-driven query filtering

### ISSUE THREAD

**Issue by voplex95** [zalando/logbook#309]
At the moment Logbook provides an ability to set up query filtering via Logbook builder. This feature takes a step forward and allows adding filters locally on Data Transfer Objects with use of annotations.

## Detailed Description

Current process of adding query filter goes as follows:
```
Logbook logbook = Logbook.builder()
    .queryFilter(replaceQuery("password", "<secret>"))
    [...]
    .build();
```
With this feature it should be possible to do it this way:
```
@Data
public class RegistrationRequest {

    @JsonProperty("username")
    private String username;

    @JsonProperty("password")
    @LogbookReplace("<secret>")
    private String password;

    [...]

}
```

## Context

Here are some points why this change is useful:
- More precise control over what data should to be hidden
- In my opinion, this approach is more resistant to code refactoring

## Possible Implementation

Don't have any concrete proposition on how to do it.
However, here are some notes:
- Solution should respect possible property name change with `@JsonProperty`.
- Maybe this feature can be part of _logbook-spring-boot-starter_

**Comment by whiskeysierra** [comment]
This is impossible with the current design and architecture of the library. Logbook deals with request and responses on a very low level. It basically consumes the body as a byte stream. It's the most common interface that works with any client/server technology we've encountered so far.

What you described is possible, but it requires a completely different set up. You'd need to write and maintain integrations with any major web framework and JSON libraries in order to achieve something like that.

> In my opinion, this approach is more resistant to code refactoring

I don't see this as a big issue in production, since refactorings like this would break your API, which is something that shouldn't be done easily.
