### ISSUE TITLE
ClassNotFoundException: org.zalando.fauxpas.ThrowingConsumer

### ISSUE THREAD

**Issue by JanWaller** [zalando/logbook#333]
With a switch to version 1.9 I get a ClassNotFoundException: org.zalando.fauxpas.ThrowingConsumer error, when using LogBook.

compile('org.zalando:logbook-spring-boot-starter:1.9.+')
does not require the org.zalando.fauxpas library

**Comment by whiskeysierra** [comment]
It does, see https://github.com/zalando/logbook/blob/1.9.0/pom.xml#L138

**Comment by JanWaller** [comment]
So, why do i get this error, and if I add it as an explicit dependency, the error is gone?

**Comment by whiskeysierra** [comment]
Ah yes, that's right. For 0.7.1 I tried the release approach described in https://axelfontaine.com/blog/dead-burried.html. As highlighted in the comments, it has the undesired side effect of leaving `${revision}` in the pom. You can see it in http://search.maven.org/#artifactdetails%7Corg.zalando%7Cfaux-pas%7C0.7.1%7Cjar:

```xml
?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
 
    <groupId>org.zalando</groupId>
    <artifactId>faux-pas</artifactId>
    <version>${revision}</version>
```

0.8.0 or higher doesn't suffer from this, since we reverted the change to the release script.

I added a hint to the release notes for 0.7.1.
