### ISSUE TITLE
Provide a way to distinguish between incoming and outgoing request/responses

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/logbook#47]

**Comment by whiskeysierra** [comment]
What do you need exactly? Because right now the API for `HttpLogFormatter` and `HttpLogWriter` allows to differentiate between requests and responses. And all default implementations use that already, see here:

- [http request](https://github.com/zalando/logbook#request)
- [http response](https://github.com/zalando/logbook#response)
- [json request](https://github.com/zalando/logbook#request-1)
- [json response](https://github.com/zalando/logbook#response-1)

**Comment by AlexanderYastrebov** [comment]
There could/should be the way to distinguish between incoming requests (say servlet) and outgoing requests (say http client). Also there is an option two have two configurations for logging incoming and outgoing requests separately.

**Comment by whiskeysierra** [comment]
Ah, I see what you meant. Yeah that could be useful.
