### ISSUE TITLE
Implement query parameter obfuscation in a less invasive way

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#50]
Right now we try to parse, modify and recreate the request URI for parameter obfuscation. Maybe there is a way to implement it e.g. using regular expressions?

**Comment by twz123** [comment]
One way to solve the issue is to replace the "parameter obfuscation" approach by a complete "request URI obfuscation". So, instead of accepting a key/value obfuscator just for query strings, a Logbook instance could accept a simple requestUriObfuscator that simply obfuscates the whole string (basically a `Function<String, String>`). This way we would have pluggable implementations that may be based on Regexes, or whatever suits best. Moreover, we're able to obfuscate path parameters as well.

I worked on this in my [request-uri-obfuscation](https://github.com/zalando/logbook/compare/master...twz123:request-uri-obfucsation) branch. A nice side-effect is that the whole problematic query-string analysis is now ripped out of the `ObfuscatedHttpRequest` and confined into its own class, that may or may not be used. The users may decide on their own.

**Comment by whiskeysierra** [comment]
> a Logbook instance could accept a simple requestUriObfuscator that simply obfuscates the whole string (basically a Function<String, String>). This way we would have pluggable implementations that may be based on Regexes, or whatever suits best. Moreover, we're able to obfuscate path parameters as well.

Cool idea. I created a pull request that changes the way logbook handles the request uri internally. Implementations of Raw/HttpRequest/Response now need to supply the request uri (without query string) and a Multimap of query parameters. I realized that the servlet API already parses and provides query parameters as a `Map<String, String[]>` so that came for free. I basically removed the QueryParameter class that could parse the query string. For the Http Client module I switched to a preexisting method in URLEncodedUtils or something that provides a way to parse the query string into a list of name/value pairs.

We could enhance it now to allow request url obfuscation in addition
