### ISSUE TITLE
HTTP log not displaying Remote Address

### ISSUE THREAD

**Issue by ortigazza** [zalando/logbook#598]
Logbook cannot print remote address by default when using http format.
## Description
When loggin requests with logbook in a http format, the remote address of the request it is not printed.
I was not able to find any hint that help me to find a way to print the remote ip address that makes the request.

I know that changing the format from http to json magically makes the remote address appearing in the log, but i want the remote address also in the http format.

Any suggestion on how to do it with zalando.logbook?

## Expected Behavior
The remote address appeared in the log with all the other informations in http format

## Actual Behavior
No remote address printed in the log with http format.

## Possible Fix
Same behaviour of the **json format**, that is to print the remote address with all the other informations when using **http format**

## Steps to Reproduce
1. Using logbook with spring boot 2.
2. Use autoconfiguration and didn't customize anything
3. configure the values of this properties:
```
logbook.include=/rest/**
logbook.write.level=INFO
logbook.write.category:com.mycompany.myproject.ws.logging
logbook.write.max-body-size=1000
logbook.format.style=http
```
4. Did not obfuscate anything
5. Try to call a rest api, and only these informations appeared
_**[INFO ] 2019-09-10 13:55:32.395 c.m.m.w.logging. - Incoming Request: c4b466fed26073d4
GET http://myurl:9000/rest/call HTTP/1.1
accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
upgrade-insecure-requests: 1
host: myurl:9000
connection: keep-alive
cache-control: max-age=0
accept-encoding: gzip, deflate
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
[INFO ] 2019-09-10 13:55:32.474 c.m.m.w.logging. - Outgoing Response: c4b466fed26073d4
Duration: 99 ms
HTTP/1.1 200 OK
Content-Length: 2
Date: Tue, 10 Sep 2019 11:55:32 GMT
Content-Type: text/html;charset=UTF-8**_

## Context
When loggin requests with logbook in a http format, the remote address of the request it is not printed.

## Your Environment
* Version used: 1.11.1
* Link to your project: spring boot 2

**Comment by whiskeysierra** [comment]
The http log format is implemented in [`DefaultHttpLogFormatter`](https://github.com/zalando/logbook/blob/master/logbook-core/src/main/java/org/zalando/logbook/DefaultHttpLogFormatter.java) and the principle behind it is that it tries to mimic the HTTP protocol as closely as possible. Since the remote address is part of TCP/IP you won't see it there, i.e. the remote address is not represented in HTTP at all.

Having said that, there are already a couple of aspects that we squeezed into the format:
- origin (`Incoming` or `Outgoing`)
- type (`Request` or `Response`)
- duration (`99 ms`)
- correlation (`c4b466fed26073d4`)

All of the above precedes the actual HTTP-style format in the logs. We could add the remote address in the same fashion, e.g.

```http
Incoming Request: c4b466fed26073d4 (192.168.0.17)
GET http://myurl:9000/rest/call HTTP/1.1
accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
```

or 

```http
Incoming Request: c4b466fed26073d4
Remote: 192.168.0.17
GET http://myurl:9000/rest/call HTTP/1.1
accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
```
