### ISSUE TITLE
Security Vulnerability in DefaultCorrolationId.java

### ISSUE THREAD

**Issue by cmardini** [zalando/logbook#709]
There appears to be a vulnerability in DefaultCorrolationId.java line 17: "Insufficient Entropy" in "java.util.Random.nextLong".

The recommended replacement is to use SecureRandom. Maybe instead of creating a new SecureRandom() each time, you could keep a static SecureRandom and call .next* on it. SecureRandom appears to be thread safe.

Chris

**Comment by whiskeysierra** [comment]
> There appears to be a vulnerability in DefaultCorrolationId.java line 17: "Insufficient Entropy" in "java.util.Random.nextLong".

Even if an attacker could predict the next correlation id, what could he/she possible do with that?

> The recommended replacement is to use SecureRandom.

For cryptographic use cases, yes. I don't see that here, to be honest. Another issue with SecureRandom is that requires a minimum system entropy in order to operate. If, by chance, you end up in a situation where there is not enough entropy available your process will just block and wait for it. That's a disaster scenario for a library like logbook that tries to be as non-invasive as possible.

**Comment by whiskeysierra** [comment]
I'm closing this, but feel free to re-open/add something if you have more information/arguments.

**Comment by cmardini** [comment]
Back with Sandy Bridge processors, I have seen cases where there isn't
enough entropy on a VM and /dev/random blocks. However, I believe that
the rdrand feature has been around for 6+ years now, which helps to provide
digital randomness.

Although I agree that there's no technical reason for changing this, there
is an advantage in having a clean vulnerability scan as it can ease
adoption. Anyone who wants to use your library wouldn't need to seek a
mitigation/exception (from a human sitting at a desk) for this one item.
But for this one item, logbook otherwise scanned clean for me.

I am not sure if SecureRandom pulls from /dev/random for each .next*() or
just for seeding. If it is just for seeding, then a singleton SecureRandom
surely will have minimal drain on /dev/random. Obviously, it would pull
more if it is for each random number generated. I also don't know how often
the random numbers are tapped in logbook.

It is up to you. I heard a security guru once say "just get a clean scan"
and I think I finished the sentence in head with: "and all your troubles
will melt away"...

Chris

**Comment by cmardini** [comment]
"Anyone who wants to use your library"... that is, anyone who has static
code analysis and, for example, needs to be PCI compliant as part of their
software development process.

**Comment by whiskeysierra** [comment]
> I am not sure if SecureRandom pulls from /dev/random for each .next*() or just for seeding.

By default it uses /dev/random for seeding once and /dev/urandom per next call, iirc. But that is configurable by setting the entropy source somewhere in the JRE, I believe.

We had UUID in the beginning and switched to the current implementation because of issues with SecureRandom (which UUID uses under the hood).

See #198

**Comment by whiskeysierra** [comment]
It's also possible to provide a custom implementation for `Correlation`. In case someone is not satisfied with the default.

**Comment by whiskeysierra** [comment]
>  I also don't know how often the random numbers are tapped in logbook.

We generate a new correlation id for each request/response pair. Frequency depends on the application.
