### ISSUE TITLE
Sensitive information in the body of OAuth2 requests not filtered by default

### ISSUE THREAD

**Issue by PascalSchumacher** [zalando/logbook#762]
If I understand https://github.com/zalando/logbook#filtering correctly sensitive information of the body of OAuth2 Request should be filtered by default:

>form-url -> client_secret and password

but senstive information is logged:

>12:25:18.332 [main] TRACE org.zalando.logbook.Logbook - Outgoing Request: f022e983472f4182
Remote: localhost
POST https://myhostname/services/oauth2/token HTTP/1.1
accept: application/json, application/*+json
accept-encoding: gzip
connection: Keep-Alive
content-length: 281
content-type: application/x-www-form-urlencoded;charset=UTF-8
host: myhostname
user-agent: okhttp/4.7.0

>grant_type=password&client_id=myid&client_secret=mysecret&username=myusername&password=mypassword

We are using logbook-spring-boot-starter, version 2.1.0 but I can replicate the behavior in a unit test where I use `Logbook.create()`.

Debugging into `DefaultLogbookFactory#create` I noticed that the `BodyFilter` is a `NonMergeableBodyFilterPair` of `org.zalando.logbook.json.CompactingJsonBodyFilter` and `org.zalando.logbook.json.AccessTokenBodyFilter`. A filter for FormUrlEncoded seems to be missing or the documentation is wrong.

**Comment by whiskeysierra** [comment]
Docs are incorrect. In `logbook-core` there is no `BodyFilter` registered by default (using service loader), but there should be one.

First, the following filter needs to be declared as a separate class:

https://github.com/zalando/logbook/blob/66a634dea13440649f118e4151bcde71711c8522/logbook-core/src/main/java/org/zalando/logbook/BodyFilters.java#L29-L35

So that it can be registered by name as a service for the `ServiceLoader`.

**Comment by whiskeysierra** [comment]
> Docs are incorrect.

Rather, the docs claim something that is desirable, but that's not the reality. Docs should stay, but behavior should be fixed.

**Comment by whiskeysierra** [comment]
I just released 2.1.2 with a fix.

**Comment by PascalSchumacher** [comment]
Thank you very much! 👍
