### ISSUE TITLE
(Spring Boot) Access to NativeWebRequest in Sink

### ISSUE THREAD

**Issue by hemju** [zalando/logbook#806]
I am implementing a Sink that stores the requests/responses in the database. I wanna link these logs to our internal models (e.g. organization). For identifying models like this, we are using `HandlerMethodArgumentResolver` from Spring. In order to reuse these resolvers, we need access to the `NativeWebRequest` from Spring.

In our Sink we only get access to the logbook request object. So basically my question is, is there a sane way to access the underlying Spring request from the Sink request object?

Update:

Access to PathVariables would also suffice. Is that possible?

**Comment by whiskeysierra** [comment]
> Access to PathVariables would also suffice. Is that possible?

Unfortunately no. There are two possible integrations for Spring:

1. Servlet Filter (Spring Web)
2. Netty Channel Handler (Spring WebFlux)

Neither of those two ways has access to any Spring-specific details of the request. In fact they run both very early in the request processing chain, *long* before Spring is even processing it.

**Comment by whiskeysierra** [comment]
In order to elaborate a bit on why that has been done the way it has:

The Spring (Boot) integration is like a cherry on top of the lower level integrations that we have. They can be used directly without the need to have Spring (Boot) at all. As an example, every user of a standard-compliant Servlet container can use logbook and it works exactly the same. The other benefit from a maintenance perspective is that we don't have to re-invent the wheel for every framework/environment as long as we are able to support the underlying technology directly.

For Servlet contains that is based on the Servlet API spec. For Netty it's similar, but slightly different, because it's not a specification, but implementation. But Netty is so dominant in the NIO-framework space that it's the defacto standard.

I hope that clarifies some of the underlying design decisions and principles.

**Comment by hemju** [comment]
Thanks for the detailed explanation and for making logbook open source! We will find another way to extract the necessary information.
