### ISSUE TITLE
The log contains Chinese, which is not displayed correctly.

### ISSUE THREAD

**Issue by tian-jeff** [zalando/logbook#870]
## Description

When print Chinese in Spring Boot projects, then looks like not right, for example:
```json
{"code":45,"name":"å¹¿è¥¿å£®æèªæ²»åº"}
```
## Expected Behavior

Print Chinese normal, like this:
```json
{"code":45,"name":"广西壮族自治区"}
```
## Actual Behavior

```json
{"code":45,"name":"å¹¿è¥¿å£®æèªæ²»åº"}
```
## Possible Fix

Must force set utf-8 encoding
```yaml
server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
```
## The root cause of this problem
![image](https://user-images.githubusercontent.com/1702836/97088366-dae55200-1662-11eb-8047-a4ed0d7ad3bc.png)
> The priority order for specifying the response body is:
> 1. explicitly per request using setCharacterEncoding and setContentType
> 2. implicitly per request using setLocale
> 3. per web application via the deployment descriptor or ServletContext.setRequestCharacterEncoding(String)
> 4. container default via vendor specific configuration
> 5. ISO-8859-1

If any possible, get encoding form somewhere else.
![image](https://user-images.githubusercontent.com/1702836/97088562-45e35880-1664-11eb-8115-1e6c16b56849.png)

## Your Environment

* Version used: ```org.zalando:logbook-spring-boot-starter:2.3.0``` & Spring Boot Ver: 2.3.4.RELEASE

**Comment by whiskeysierra** [comment]
> ISO-8859-1

Is that the fallback from Tomcat or defined in the Servlet Spec?

**Comment by tian-jeff** [comment]
Thx for you reply, I think this is fallback from Tomcat.

**Comment by whiskeysierra** [comment]
> I think this is fallback from Tomcat.

Ok, if that is in fact the case (could you verify that somehow?), then I see the following options:

1. We leave it as it is. Works for UTF-8, but breaks for everything else. Bad user experience for some users and no possible workaround.
2. We leave UTF-8 as our default fallback, but we make it configurable. Either with a system property or something alike. It will work for most users out of the box and those that need something different have something to work around the issue.
3. We could try to detect in which servlet container we're actually running (inspecting class names maybe?) and change our fallback charset accordingly.

Option 3 puts some burden on Logbook to maintain a good set of servlet container default charsets and increases the scope of tests a bit (in case we actually want to test that in different servers). But on the other hand it would give the best user experience because it will just magically do the right thing for all users.

**Comment by whiskeysierra** [comment]
I could see myself implementing Option 3, but I'd need someone to provide me a pull request with a failing test case for chinese characters.

@tian-jeff @wpt191 @xudamiao-hub

**Comment by whiskeysierra** [comment]
Maybe ISO-8859-1 is actually the default of most (all?) servlet containers?

**Comment by whiskeysierra** [comment]
Looks like it's mandated by the spec:

> ## 3.12 Request data encoding
>
> Currently, many browsers do not send a char encoding qualifier with the Content- Type header, leaving open the determination of the character encoding for reading HTTP requests. In the absence of a char encoding qualifier, if the Content-Type is `application/x-www-form-urlencoded`, the default encoding the container uses to create the request reader and parse POST data must be `US-ASCII`. Any `%nn` encoded values must be decoded to ISO-8859-1. **For any other `Content-Type`, if none has been specified by the client request, web application or container vendor specific configuration (for all web applications in the container), the default encoding of a request the container uses to create the request reader and parse POST data must be ISO-8859-1.** However, in order to indicate to the developer the absence of a char encoding qualifier, the container must return `null` from the `getCharacterEncoding()` method."

**Comment by whiskeysierra** [comment]
Ok, so in that case the fix seems to be to change the fallback charset to `ISO-8859-1` for requests/responses in the `logbook-servlet` module.

**Comment by tian-jeff** [comment]
Great! Thx for you efforts.

**Comment by sohtsuka** [comment]
I have the same issue with Japanese characters.

The problem is the fallback encoding never being used, not the encoding itself.
Unlike `ServletRequest#getCharacterEncoding()`, `ServletResponse#getCharacterEncoding()`
returns `ISO-8859-1` when `setCharacterEncoding()` has not been called. So

    return Optional.ofNullable(getCharacterEncoding()).map(Charset::forName).orElse(UTF_8);

always returns `ISO-8859-1` as the fallback encoding.

Forciblly setting the response encoding in Spring Boot configuration

    server.servlet.encoding.charset=UTF-8
    server.servlet.encoding.force-response=true

solves the issue, but setting this makes the Content-Type response header
add `;charset=UTF-8` in all the responses (including images).

The only applicable solution is adding ";charset=UTF-8" to request mappings:

    @GetMapping(value={"/demo"}, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public DemoResponse () {

But adding `charset` to JSON responses is violating the spec and has been deprecated by Spring Team....
https://github.com/spring-projects/spring-framework/issues/22788

I'm at the dead end.

**Comment by whiskeysierra** [comment]
The fix will be part of 2.5.0.

**Comment by kyle18th** [comment]
@sohtsuka @whiskeysierra Always return `ISO-8859-1` is right, and force response charset to `UTF-8` is not a good idea because spring 5.2 deprecate `application/json;charset=UTF-8`. According to `RFC 8259`, JSON text MUST be encoded using `UTF-8`, so i think when response content type is `application/json`, `LocalResponse` can use UTF-8 charset.

**Comment by sohtsuka** [comment]
@whiskeysierra 
Is it possible to reconsider the fix? As @kyle18th commented, Spring Boot does not provide the (legal) way to set the response charset when the content type is `application/json`.

This controller:
```java
@RestController
public class Controller {
    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    public List<String> demo() {
	// "world" in Kanji: https://en.wiktionary.org/wiki/%E4%B8%96%E7%95%8C
	return List.of("世界");
    }
}
```
produces the UTF-8 JSON response below. It works without setting the response charset.
```
["世界"]
```

However, in the Logbook's log message, the response body is garbled.
```
2021-07-21 19:38:59.398 TRACE 11671 --- [nio-8080-exec-1] org.zalando.logbook.Logbook              : {"origin":"local","type":"response","correlation":"ce55b6230e12728d","duration":437,"protocol":"HTTP/1.1","status":200,"headers":{"Connection":["keep-alive"],"Content-Type":["application/json"],"Date":["Wed, 21 Jul 2021 19:38:59 GMT"],"Keep-Alive":["timeout=60"],"Transfer-Encoding":["chunked"]},"body":["ããã«ã¡ã¯"]}
```

This seems to be because Logbook uses the fallback encoding (ISO-8859-1) even if the document is JSON.

Setting the response character encoding explictly:
```java
@GetMapping(produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
```
fixes the log message.
```
2021-07-21 19:59:25.295 TRACE 12606 --- [nio-8080-exec-4] org.zalando.logbook.Logbook              : {"origin":"local","type":"response","correlation":"ac7dc50a7cf0fcd0","duration":5,"protocol":"HTTP/1.1","status":200,"headers":{"Connection":["keep-alive"],"Content-Type":["application/json;charset=UTF-8"],"Date":["Wed, 21 Jul 2021 19:59:25 GMT"],"Keep-Alive":["timeout=60"],"Transfer-Encoding":["chunked"]},"body":["世界"]}
```
But `APPLICATION_JSON_UTF8_VALUE` is deprecated and should not be used.

**Comment by whiskeysierra** [comment]
Thanks for the thorough investigation. Doing this requires two steps:
- Centralize the charset fallback handling by introducing a single method that every adapter delegates to. We should pass the content type, if there was one.
- Change the fallback from just returning ISO-8859-1 to checking the content type first and handle Json differently.

**Comment by sohtsuka** [comment]
Thanks! That would be very helpful.
I'm using the workaround below, but this is not ideal.

```java
@Component
@Order(Ordered.LOWEST_PRECEDENCE - 1) // Just before LogbookFilter
public class CharsetFilter extends OncePerRequestFilter {
  @Override
  protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
    FilterChain filterChain) throws ServletException, IOException {
    HttpServletResponseWrapper wrappedResponse = new HttpServletResponseWrapper(response) {
      @Override
      public String getCharacterEncoding() {
        String encoding = super.getCharacterEncoding();
        if (MediaType.APPLICATION_JSON_VALUE.equals(getContentType()) &&
            !StandardCharsets.UTF_8.name().contentEquals(encoding)) {
          return StandardCharsets.UTF_8.name();
        }
        return encoding;
      }
    };
    filterChain.doFilter(request, wrappedResponse);
  }
}
```

**Comment by laomazk** [comment]
`    @Bean
    @ConditionalOnMissingBean(RequestFilter.class)
    public RequestFilter requestFilter() {
        RequestFilter requestFilter = RequestFilters.defaultValue();
        return RequestFilter.merge(requestFilter, r -> new HttpRequest() {
			......

            @Override
            public String getBodyAsString() throws IOException {
                // https://github.com/zalando/logbook/issues/870
                return new String(r.getBody());
            }

            ......
        });
    }`
I write a bean like this, and it works correctly.

**Comment by nhmarujo** [comment]
Hi @kasmarian. You guys have any fix in mind for this one? 🙂 Thanks

**Comment by nhmarujo** [comment]
Well we were trying something similar to the last comment, but with `RequestFilters.replaceBody`:
```java
@Bean
@ConditionalOnMissingBean(RequestFilter.class)
public RequestFilter requestFilter() {
    return RequestFilter.merge(RequestFilters.defaultValue(),
            RequestFilters.replaceBody(message -> {
                try {
                    return new String(message.getBody());
                } catch (IOException e) {
                   throw new RuntimeException("Error executing replaceBody", e);
                }
            }));
}
```

We still need to double-check it, but didn't seem to do the trick.

**Comment by lricardo** [comment]
Some updates on @nhmarujo comment (we work at the same team). 

It will work depending on wether we are having the problem in request or response. In our case, we were having the correct value on request but not in the response (for some reason that is unknown for us right now).

As result, I've changed the response filter instead, to something similar:

```java
    @Bean
    @ConditionalOnMissingBean({ResponseFilter.class})
    public ResponseFilter responseFilter() {
        return ResponseFilter.merge(ResponseFilters.defaultValue(), ResponseFilters.replaceBody(response -> {
            try {
                return new String(response.getBody(), UTF_8);
            } catch (IOException e) {
                throw new RuntimeException("Error filtering the response", e);
            }
        }));
    }
```

@kasmarian We have one doubt, though: does filtering the response will only have impacts on logbook or it will also have the side effect to manipulate the underlying request/response? Thanks in advance

**Comment by kasmarian** [comment]
>  In our case, we were having the correct value on request but not in the response (for some reason that is unknown for us right now).
The reason is that spring would add UTF-8 encoding to requests by default with `org.springframework.web.filter.CharacterEncodingFilter` if it's not set by other filters already. But for responses, it only adds the encoding if you explicitly set `server.servlet.encoding.force-response=true`. When no charset is set explicitly, HttpServletResponse implementations fall back to `ISO-8859-1` (as per [this comment](https://github.com/zalando/logbook/issues/870#issuecomment-723290269).

**Comment by kasmarian** [comment]
Hi everyone, I've created a PR (https://github.com/zalando/logbook/pull/1521) to use UTF-8 for JSON content types when nothing else is explicitly set. Would this fix work for your use cases? Please take a look and leave your comments if something is missed.

**Comment by lricardo** [comment]
Hi @kasmarian

I've check your PR and I believe that will fix our use-cases.

Thank you very much for your effort solving this problem

**Comment by nhmarujo** [comment]
I second what @lricardo said. I also believe it will fix it. Thank you

**Comment by kasmarian** [comment]
The PR is merged and will be available in the next release. I'd like to resolve this issue. Feel free to reopen it, if it's not fully addressed.

**Comment by rishiraj88** [comment]
Thanks.

**Comment by davidtothdev** [comment]
Hi all! 
I'm having a similar issue, In my case the problem occurs when I'm using  `org.zalando:logbook-spring-boot-starter:3.1.0` in a spring boot 3.1.0 project with a html thymeleaf template. When I use the dependency mentioned before the application fails to properly convert special characters, but when I revert to `org.zalando:logbook-spring-boot-starter:3.0.0` it looks like the problem no longer present.

**Comment by kasmarian** [comment]
@davidtothdev could you share more details about your use case? Or, if possible, create an example repo, where the issue is reproducible. That would help a lot.

**Comment by nhmarujo** [comment]
Hi @kasmarian . We are facing a similar issue with logbook and thymeleaf. In our case is making some emojis that we were displaying to show as question marks. I will try to create a minimal app to reproduce the issue.

**Comment by nhmarujo** [comment]
@kasmarian I just a did of debug on the app @lricardo provided and I can see that problem happens on `HttpMessage:44` (it should be resolving to `UTF-8`):
![image](https://github.com/zalando/logbook/assets/18704110/a022247a-56bb-4183-82d4-153f2a1bcc58)

Looking at the execution on `LocalResponse:181` I can see that it is not being able to fetch the content-type header (or any other header, for all that is worth), so it can't parse the correct charset to use and fallback to `ISO-8859-1`:
![image](https://github.com/zalando/logbook/assets/18704110/6b2ec34b-8724-45f6-9fe8-388437b2ec44)

I wonder why no headers are fetched, as I can clearly see them in response on the browser:
![image](https://github.com/zalando/logbook/assets/18704110/80e55372-2abf-4fc5-a705-c523678fe3cb)

Maybe they are not available at that stage of the code execution??

I also checked what the parser would decide if we managed to get the header and I can see it would decide correctly:
![image](https://github.com/zalando/logbook/assets/18704110/0f57f98e-d73a-4258-a349-3f843d4ce77a)

**Comment by kasmarian** [comment]
@nhmarujo yes, it looks like relying purely on the header would not work in case of Thymeleaf (and probably other implementations) as the content-type header is not yet available. I'll open a PR to use `getCharacterEncoding()` method in case of content-type header is empty.

**Comment by nhmarujo** [comment]
Thank you @kasmarian. That sounds good 😊

**Comment by kasmarian** [comment]
ok, another fix is merged. Hope this one doesn't break anything else :smile:

**Comment by nhmarujo** [comment]
Thank you @kasmarian ! Any ETA for a release?

**Comment by kasmarian** [comment]
> Thank you @kasmarian ! Any ETA for a release?

I think we can do it this week. Let me chat with the team about it
