### ISSUE TITLE
Please add CHANGELOG.md :)

### ISSUE THREAD

**Issue by pierrefevrier** [zalando/logbook#944]
Everything is in the title :)

**Comment by whiskeysierra** [comment]
This has been on my personal TODO/wishlist for a while. Unfortunately I don't see this happening any time soon.

**Comment by pierrefevrier** [comment]
How can we know what append between versions of Logbook without it (except by watching code) ?

**Comment by whiskeysierra** [comment]
I don't have a satisfying answer apart from using https://github.com/zalando/logbook/compare/. This is just one of many open source projects where I'm the only maintainer. I've since switched jobs and just don't have the time to this unless I'm willing to take time off of family time, personal time or work.

**Comment by pierrefevrier** [comment]
Thank you for the job you are doing.  
Is there anything on the roadmap to help you make Logbook continue to shine ?

**Comment by sokomishalov** [comment]
I think using [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) would be great (and easy) for the start
