### ISSUE TITLE
Request params in body are erased by logbook

### ISSUE THREAD

**Issue by Slmba** [zalando/logbook#945]
When I enable logbook - the spring web mvc method with request query params stops to work.
![image](https://user-images.githubusercontent.com/9422826/106781459-23e17500-665a-11eb-9649-a4657cd3ff25.png)
When I exclude this request in settings:
![image](https://user-images.githubusercontent.com/9422826/106781569-41aeda00-665a-11eb-9661-6fd902bb0321.png)
Everything works:
![image](https://user-images.githubusercontent.com/9422826/106781766-76bb2c80-665a-11eb-9fae-b04267e419b9.png)
SO, the simple spring MVC method:
![image](https://user-images.githubusercontent.com/9422826/106782020-c39f0300-665a-11eb-909f-94bd32825dfe.png)

Is it possible to fix it?
I see - ServletWebRequest contains this parameters in 'parametersMap'.
But when enable logging for this endpoint - 'parametersMap' doesn't contains it.

I use logbook-spring-boot-starter 2.4.1.

**Comment by whiskeysierra** [comment]
Please read https://github.com/zalando/logbook#form-requests and the preceding paragraph. You can decide whether logging works or your application, but you can't have both because of how the servlet api works.

**Comment by Slmba** [comment]
Body also cannot be read,

**Comment by Slmba** [comment]
> Please read https://github.com/zalando/logbook#form-requests and the preceding paragraph. You can decide whether logging works or your application, but you can't have both because of how the servlet api works.

But how it works for json body?

**Comment by whiskeysierra** [comment]
Servlet only handle form requests in a special way. They throw query and form parameters in one big map and they only allow you to use either getInputStream or getParameters but not both. It's a destructive operation and in a nutshell really bad design.

JSON bodies and every other kind of request work fine because they all use getInputStream exclusively.

**Comment by Slmba** [comment]
> Servlet only handle form requests in a special way. They throw query and form parameters in one big map and they only allow you to use either getInputStream or getParameters but not both. It's a destructive operation and in a nutshell really bad design.
> 
> JSON bodies and every other kind of request work fine because they all use getInputStream exclusively.

But logbook logs json body. And then spring MVC read it to construct the object. So its double read. And it works. 
But form request can only once? What i understand wrong?

**Comment by whiskeysierra** [comment]
> So its double read.

It's read one, but logbook buffers it, so the body can be used for logging as well.

## How it works for non-form requests, e.g. JSON

- The Logbook servlet filter intercepts the request
  - It possibly runs before other filters
  - It definitely runs before the servlet
- Logbook buffers the input stream
- A downstream filter or the servlet will call `getInputStream`
  - The returned input stream will return the buffered data

## How it works for form request

- The Logbook servlet filter intercepts the request
  - It possibly runs before other filters
  - It definitely runs before the servlet
- Logbook buffers the input stream
- A downstream filter or the servlet can call either `getInputStream`...
  - The returned input stream will return the buffered data
  - Everything is fine, in this case
- **or** it can call one of the `getParameter*` methods
  - `getParameter*` is a special method because it causes the input stream to be consumed and the parsed as form parameters
  - the parameters are then cached
  - the input stream can't be consumed again
  - Logbook does **not** intercept this call in any way
  - Since the input stream is already consumed by Logbook, there are no parameters to parse

In this scenario you get proper logging, but the downstream servlet fails to read the parameters.
The alternative to this is to do it the other way around. Don't buffer the input stream and let the downstream servlet properly cause parameters to be parsed. Then you'd get proper behavior on the application side, but logging would show an empty body (since Logbook never read it).

You can pick between these two options (see my link to the README from earlier).

## Root cause

The root cause is that the Servlet API has essentially two ways that cause the input stream to be consumed:

1. Calling and consuming `getInputStream`
2. Calling any of the `getParameters*` methods

A filter/servlet can only ever call one of them and expect it to work. Once someone called either of them, that decision is made and can't be reversed for that particular request (hence it's a destructive operation). It's something that you can't reliable and correctly do in a filter without breaking someone's code. 

If Logbook consumes the input stream then parameters don't work. If Logbook consumes the parameters then the input stream won't work. Logbook has no way of knowing what a downstream filter/servlet is going to do. 

## Options

Options that you have right now is to decide which behavior you want to specify the setting accordingly. It's a trade-off that the user has to make.

An alternative would be that Logbook is doing one of the following two:

1. Logbook consumes the input stream but also parses parameters if it's a form request and returns them correctly as parameters. Parsing form parameters is not trivial and should better be left to servlet containers, hence it's not implemented.
2. Logbook consumes the parameters and reconstructs the body out of the parameters. The parameters are a mix of query and body parameters and there is no reliable way to tell them apart. Hence it's impossible to reliably reconstruct the body, hence it's not implemented.

## Conclusion
There is no clean way out of this that makes everyone happy. It's a classic trade-off and the current compromise is to make everyone equally unhappy...

This issue only exists for the Logbook integration using the Servlet API. Any other module (JAX-RS, OKHttp, Apache HTTP Client, Netty, etc.) don't suffer from this.
